# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc35f076765ab7322cee6c472b3363159edcd8b840a84560f82d377a44a379162e9a8b85e7423010176d95c560823a39582611b3d595f985355e4546550f85aa

test:
  secret_key_base: 5a3779427b546e112944f0bfeb46486e6b278549c6f301e5e93ddc07ff46837f783d46dfabb197ce35b8c885f2c82d8f262d86307ad1c4c2bb297f328587ac7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
